// Nguồn sự thật cho tên kênh IPC. Main đăng ký handle, preload gọi invoke.
export const IPC = {
  setupGetStatus: 'setup:getStatus',
  setupStart: 'setup:start',
  recorderStart: 'recorder:start',
  recorderStop: 'recorder:stop',
  importFile: 'recorder:importFile',
  recorderStatus: 'recorder:status',
  pipelineState: 'pipeline:state',
  pipelineReset: 'pipeline:reset',
  meetingsList: 'meetings:list',
  meetingsGet: 'meetings:get',
  meetingsOpenFolder: 'meetings:openFolder',
  meetingsOpenPdf: 'meetings:openPdf',
  meetingsExportPdf: 'meetings:exportPdf',
  meetingsWriteMinutes: 'meetings:writeMinutes',
  meetingsSaveBienban: 'meetings:saveBienban',
  meetingsDelete: 'meetings:delete',
  meetingsSetProfile: 'meetings:setProfile',
  meetingsFindReplace: 'meetings:findReplace',
  meetingsRevise: 'meetings:revise',
  meetingsProcess: 'meetings:process',
  meetingsGenerateTitle: 'meetings:generateTitle',
  meetingsSetTitle: 'meetings:setTitle',
  meetingsSearch: 'meetings:search',
  meetingsWikiNote: 'meetings:wikiNote',
  wikiList: 'wiki:list',
  wikiGet: 'wiki:get',
  wikiCreate: 'wiki:create',
  wikiSave: 'wiki:save',
  wikiDelete: 'wiki:delete',
  wikiResolve: 'wiki:resolve',
  wikiAsk: 'wiki:ask',
  wikiExportPdf: 'wiki:exportPdf',
  devicesList: 'devices:list',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  engineCheck: 'engine:check',
  glossaryGet: 'glossary:get',
  glossarySave: 'glossary:save',
  glossaryReveal: 'glossary:reveal',
  profilesList: 'profiles:list',
  profilesCreate: 'profiles:create',
  profilesRename: 'profiles:rename',
  tasksList: 'tasks:list',
  tasksCreate: 'tasks:create',
  tasksCreateMany: 'tasks:createMany',
  tasksUpdate: 'tasks:update',
  tasksDelete: 'tasks:delete',
  openExternal: 'shell:openExternal',
  openScreenRecordingPrefs: 'shell:openScreenRecordingPrefs',
  appVersion: 'app:version'
} as const

// Sự kiện main -> renderer (webContents.send)
export const IPC_EVENTS = {
  setupProgress: 'setup:progress',
  pipelineProgress: 'pipeline:progress',
  recorderChanged: 'recorder:changed'
} as const
